import variables from './variables';

export default {
  primary: variables['pink-01'],
  secondary: variables['violet-01'],
  background: variables['pink-04'],
  white: variables.white,
  black: variables.black,
  grey0: variables.black,
  grey1: variables['gray-01'],
  grey2: variables['gray-02'],
  grey3: variables['gray-03'],
  grey4: variables['gray-04'],
  grey5: variables.white,
  greyOutline: variables['gray-01'],
  searchBg: variables['gray-01'],
  success: variables['green-03'],
  error: variables['red-01'],
  warning: variables['yellow-01'],
  divider: variables['gray-01'],
  disabled: variables['gray-01'],
  colorA: variables['pink-02'],
  colorB: variables['pink-03'],
  colorC: variables['green-02'],
  colorD: variables['green-01'],
  colorE: variables['green-04'],
  colorF: variables['red-02'],
  colorG: variables['red-03'],
  colorH: variables['red-04'],
  colorI: variables['violet-02'],
  colorK: variables['violet-03'],
  colorL: variables['yellow-02'],
  colorM: variables['yellow-03'],
  colorN: variables['rose-01'],
  colorO: variables['rose-02'],
  colorP: variables['rose-03'],
  colorQ: variables['skyblue-01'],
  colorR: variables['skyblue-02'],
  colorS: variables['skyblue-03'],
  colorT: variables['beige-01'],
  colorU: variables['beige-02'],
  colorW: variables['beige-03'],
  colorX: variables['red-05'],
};
